---
- QualifiedName: regint
  NewName: regint_old_b026324c6904b2a
- QualifiedName: gb18030_mbc_to_code
  NewName: gb18030_mbc_to_code_old_b026324c6904b2a
- QualifiedName: OPENSSL_sk_dup
  NewName: OPENSSL_sk_dup_old_b026324c6904b2a
- QualifiedName: DEBUG_GB18030
  NewName: DEBUG_GB18030_old_b026324c6904b2a 
- QualifiedName: state
  NewName: state_old_b026324c6904b2a 
- QualifiedName: gb18030_left_adjust_char_head
  NewName: gb18030_left_adjust_char_head_old__b026324c6904b2a
